"""add bloom tables

Revision ID: 0cd2b9b1c455
Revises: 486828ee76a2
Create Date: 2025-10-02 17:03:00.498089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cd2b9b1c455'
down_revision: Union[str, None] = '486828ee76a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloom_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.String(length=12), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('date_of_max_ebi', sa.Date(), nullable=False),
    sa.Column('ebi_value', sa.Float(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['user_mundiai_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bloom_observations_map_date', 'bloom_observations', ['map_id', 'date_of_max_ebi'], unique=False)
    op.create_index('ix_bloom_observations_map_lat_lon', 'bloom_observations', ['map_id', 'latitude', 'longitude'], unique=False)
    op.create_table('bloom_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.String(length=12), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('predicted_bloom_start', sa.Date(), nullable=False),
    sa.Column('predicted_bloom_peak', sa.Date(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['user_mundiai_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bloom_predictions_map_lat_lon', 'bloom_predictions', ['map_id', 'latitude', 'longitude'], unique=False)
    op.create_index('ix_bloom_predictions_map_peak', 'bloom_predictions', ['map_id', 'predicted_bloom_peak'], unique=False)
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('map_id', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('tool_call_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tool_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tool_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('message_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['map_id'], ['user_mundiai_maps.id'], name=op.f('messages_map_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.drop_index('ix_bloom_predictions_map_peak', table_name='bloom_predictions')
    op.drop_index('ix_bloom_predictions_map_lat_lon', table_name='bloom_predictions')
    op.drop_table('bloom_predictions')
    op.drop_index('ix_bloom_observations_map_lat_lon', table_name='bloom_observations')
    op.drop_index('ix_bloom_observations_map_date', table_name='bloom_observations')
    op.drop_table('bloom_observations')
    # ### end Alembic commands ###