"""pest_diagnosis

Revision ID: 2aadec30694a
Revises: 0cd2b9b1c455
Create Date: 2025-10-04 05:31:19.549389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aadec30694a'
down_revision: Union[str, None] = '0cd2b9b1c455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pest_diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.String(length=12), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('species_detected', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('recommended_treatments', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['user_mundiai_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pest_diagnosis_map_lat_lon', 'pest_diagnosis', ['map_id', 'latitude', 'longitude'], unique=False)
    op.create_index('ix_pest_diagnosis_species', 'pest_diagnosis', ['species_detected'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pest_diagnosis_species', table_name='pest_diagnosis')
    op.drop_index('ix_pest_diagnosis_map_lat_lon', table_name='pest_diagnosis')
    op.drop_table('pest_diagnosis')
    # ### end Alembic commands ###